name: assignment
description: "CourtNow app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  mobile_scanner: ^7.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  supabase_flutter: ^2.8.4

  # QR code generation
  qr_flutter: ^4.1.0

  # Offline / local storage
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.4+4   # required for Windows/Linux desktop
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  http: ^1.6.0
  image_picker: ^1.1.2
  timezone: ^0.10.1
  flutter_local_notifications: ^19.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/admin/
    - assets/images/booking/
#    - assets/images/facility/
    - assets/images/home/
    - assets/images/notification/
    - assets/images/party/
    - assets/images/profile/
    - assets/images/logo.png
